# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginForm(object):
    def setupUi(self, loginForm):
        loginForm.setObjectName("loginForm")
        loginForm.resize(625, 567)
        self.loginWidget = QtWidgets.QWidget(loginForm)
        self.loginWidget.setGeometry(QtCore.QRect(19, 30, 591, 131))
        self.loginWidget.setObjectName("loginWidget")
        self.logoLabel = QtWidgets.QLabel(self.loginWidget)
        self.logoLabel.setGeometry(QtCore.QRect(20, 10, 101, 111))
        self.logoLabel.setStyleSheet("border-image: url(:/images/Icons/Logo-APU-200.png);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.titleLabel = QtWidgets.QLabel(self.loginWidget)
        self.titleLabel.setGeometry(QtCore.QRect(130, 20, 411, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setTextFormat(QtCore.Qt.RichText)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.loginPageWidget = QtWidgets.QWidget(loginForm)
        self.loginPageWidget.setGeometry(QtCore.QRect(20, 170, 591, 381))
        self.loginPageWidget.setObjectName("loginPageWidget")
        self.usernameInput = QtWidgets.QLineEdit(self.loginPageWidget)
        self.usernameInput.setGeometry(QtCore.QRect(40, 110, 509, 20))
        self.usernameInput.setObjectName("usernameInput")
        self.passwordInput = QtWidgets.QLineEdit(self.loginPageWidget)
        self.passwordInput.setGeometry(QtCore.QRect(40, 230, 509, 20))
        self.passwordInput.setText("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.loginPageLabel = QtWidgets.QLabel(self.loginPageWidget)
        self.loginPageLabel.setGeometry(QtCore.QRect(40, 17, 509, 67))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.loginPageLabel.setFont(font)
        self.loginPageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginPageLabel.setObjectName("loginPageLabel")
        self.usernameLabel = QtWidgets.QLabel(self.loginPageWidget)
        self.usernameLabel.setGeometry(QtCore.QRect(40, 70, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.loginPageWidget)
        self.passwordLabel.setGeometry(QtCore.QRect(40, 190, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passwordLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.registerButton = QtWidgets.QPushButton(self.loginPageWidget)
        self.registerButton.setGeometry(QtCore.QRect(40, 310, 101, 41))
        self.registerButton.setObjectName("registerButton")
        self.loginButton = QtWidgets.QPushButton(self.loginPageWidget)
        self.loginButton.setGeometry(QtCore.QRect(440, 310, 101, 41))
        self.loginButton.setObjectName("loginButton")

        self.retranslateUi(loginForm)
        QtCore.QMetaObject.connectSlotsByName(loginForm)

    def retranslateUi(self, loginForm):
        _translate = QtCore.QCoreApplication.translate
        loginForm.setWindowTitle(_translate("loginForm", "Form"))
        self.titleLabel.setText(_translate("loginForm", "APU Workspace@Facial Emotion Recognition System"))
        self.loginPageLabel.setText(_translate("loginForm", "LOGIN PAGE"))
        self.usernameLabel.setText(_translate("loginForm", "Username"))
        self.passwordLabel.setText(_translate("loginForm", "Password"))
        self.registerButton.setText(_translate("loginForm", "Register"))
        self.loginButton.setText(_translate("loginForm", "Login"))
from UI import res

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QWidget()
#     ui = Ui_loginForm()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
