# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        
        # Set main window properties
        MainWindow.setStyleSheet("background-color: #f5f5f5;")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.loginPageWidget = QtWidgets.QWidget(self.centralwidget)
        self.loginPageWidget.setGeometry(QtCore.QRect(100, 200, 600, 300))
        self.loginPageWidget.setObjectName("loginPageWidget")
        self.loginPageWidget.setStyleSheet("background-color: white; border-radius: 10px;")
        
        self.usernameInput = QtWidgets.QLineEdit(self.loginPageWidget)
        self.usernameInput.setGeometry(QtCore.QRect(40, 110, 509, 40))
        self.usernameInput.setObjectName("usernameInput")
        self.usernameInput.setStyleSheet("""
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 15px;
        """)
        
        self.passwordInput = QtWidgets.QLineEdit(self.loginPageWidget)
        self.passwordInput.setGeometry(QtCore.QRect(40, 180, 509, 40))
        self.passwordInput.setText("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.passwordInput.setStyleSheet("""
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        """)
        
        self.loginPageLabel = QtWidgets.QLabel(self.loginPageWidget)
        self.loginPageLabel.setGeometry(QtCore.QRect(40, 20, 509, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        self.loginPageLabel.setFont(font)
        self.loginPageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginPageLabel.setObjectName("loginPageLabel")
        self.loginPageLabel.setStyleSheet("color: #333;")
        
        self.usernameLabel = QtWidgets.QLabel(self.loginPageWidget)
        self.usernameLabel.setGeometry(QtCore.QRect(40, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameLabel.setStyleSheet("color: #666;")
        
        self.passwordLabel = QtWidgets.QLabel(self.loginPageWidget)
        self.passwordLabel.setGeometry(QtCore.QRect(40, 150, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passwordLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordLabel.setStyleSheet("color: #666;")
        
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.loginPageWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 240, 509, 50))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.buttonLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("buttonLayout")
        
        self.registerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.registerButton.setObjectName("registerButton")
        self.registerButton.setStyleSheet("""
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
        """)
        self.buttonLayout.addWidget(self.registerButton)
        
        self.loginButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.loginButton.setObjectName("loginButton")
        self.loginButton.setStyleSheet("""
            background-color: #008CBA;
            color: white;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
        """)
        self.buttonLayout.addWidget(self.loginButton)
        
        self.loginWidget = QtWidgets.QWidget(self.centralwidget)
        self.loginWidget.setGeometry(QtCore.QRect(40, 20, 720, 150))
        self.loginWidget.setObjectName("loginWidget")
        
        self.logoLabel = QtWidgets.QLabel(self.loginWidget)
        self.logoLabel.setGeometry(QtCore.QRect(20, 10, 101, 111))
        self.logoLabel.setStyleSheet("border-image: url(:/images/Icons/Logo-APU-200.png);")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        
        self.titleLabel = QtWidgets.QLabel(self.loginWidget)
        self.titleLabel.setGeometry(QtCore.QRect(140, 20, 560, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setTextFormat(QtCore.Qt.RichText)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setStyleSheet("color: #333;")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.loginPageLabel.setText(_translate("MainWindow", "Login"))
        self.usernameLabel.setText(_translate("MainWindow", "Username"))
        self.passwordLabel.setText(_translate("MainWindow", "Password"))
        self.registerButton.setText(_translate("MainWindow", "Register"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.titleLabel.setText(_translate("MainWindow", "APU Workspace@Facial Emotion Recognition System"))
        
from View import res