# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        
        # Set main window properties
        MainWindow.setStyleSheet("background-color: #f5f5f5;")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.regPageWidget = QtWidgets.QWidget(self.centralwidget)
        self.regPageWidget.setGeometry(QtCore.QRect(100, 150, 600, 400))
        self.regPageWidget.setObjectName("regPageWidget")
        self.regPageWidget.setStyleSheet("background-color: white; border-radius: 10px;")
        
        self.usernameRegInput = QtWidgets.QLineEdit(self.regPageWidget)
        self.usernameRegInput.setGeometry(QtCore.QRect(40, 110, 509, 40))
        self.usernameRegInput.setObjectName("usernameRegInput")
        self.usernameRegInput.setStyleSheet("""
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 15px;
        """)
        
        self.passwordRegInput = QtWidgets.QLineEdit(self.regPageWidget)
        self.passwordRegInput.setGeometry(QtCore.QRect(40, 180, 509, 40))
        self.passwordRegInput.setText("")
        self.passwordRegInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordRegInput.setObjectName("passwordRegInput")
        self.passwordRegInput.setStyleSheet("""
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        """)
        
        self.passwordRegInput_2 = QtWidgets.QLineEdit(self.regPageWidget)
        self.passwordRegInput_2.setGeometry(QtCore.QRect(40, 250, 509, 40))
        self.passwordRegInput_2.setText("")
        self.passwordRegInput_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordRegInput_2.setObjectName("passwordRegInput_2")
        self.passwordRegInput_2.setStyleSheet("""
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        """)
        
        self.loginPageLabel = QtWidgets.QLabel(self.regPageWidget)
        self.loginPageLabel.setGeometry(QtCore.QRect(40, 20, 509, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        self.loginPageLabel.setFont(font)
        self.loginPageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginPageLabel.setObjectName("loginPageLabel")
        self.loginPageLabel.setStyleSheet("color: #333;")
        
        self.usernameRegLabel = QtWidgets.QLabel(self.regPageWidget)
        self.usernameRegLabel.setGeometry(QtCore.QRect(40, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.usernameRegLabel.setFont(font)
        self.usernameRegLabel.setObjectName("usernameRegLabel")
        self.usernameRegLabel.setStyleSheet("color: #666;")
        
        self.passwordRegLabel = QtWidgets.QLabel(self.regPageWidget)
        self.passwordRegLabel.setGeometry(QtCore.QRect(40, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.passwordRegLabel.setFont(font)
        self.passwordRegLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passwordRegLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.passwordRegLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.passwordRegLabel.setObjectName("passwordRegLabel")
        self.passwordRegLabel.setStyleSheet("color: #666;")
        
        self.passwordRegLabel_2 = QtWidgets.QLabel(self.regPageWidget)
        self.passwordRegLabel_2.setGeometry(QtCore.QRect(40, 220, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.passwordRegLabel_2.setFont(font)
        self.passwordRegLabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passwordRegLabel_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.passwordRegLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.passwordRegLabel_2.setObjectName("passwordRegLabel_2")
        self.passwordRegLabel_2.setStyleSheet("color: #666;")
        
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.regPageWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 310, 511, 50))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.buttonLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("buttonLayout")
        
        self.backButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.backButton.setObjectName("backButton")
        self.backButton.setStyleSheet("""
            background-color: #f44336;
            color: white;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
        """)
        self.buttonLayout.addWidget(self.backButton)
        
        self.regButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.regButton.setObjectName("regButton")
        self.regButton.setStyleSheet("""
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
        """)
        self.buttonLayout.addWidget(self.regButton)
        
        self.loginWidget = QtWidgets.QWidget(self.centralwidget)
        self.loginWidget.setGeometry(QtCore.QRect(40, 10, 720, 150))
        self.loginWidget.setObjectName("loginWidget")
        
        self.logoLabel = QtWidgets.QLabel(self.loginWidget)
        self.logoLabel.setGeometry(QtCore.QRect(20, 10, 101, 111))
        self.logoLabel.setStyleSheet("border-image: url(:/images/Icons/Logo-APU-200.png);")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        
        self.titleLabel = QtWidgets.QLabel(self.loginWidget)
        self.titleLabel.setGeometry(QtCore.QRect(140, 20, 560, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setTextFormat(QtCore.Qt.RichText)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setStyleSheet("color: #333;")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Register"))
        self.loginPageLabel.setText(_translate("MainWindow", "Register"))
        self.usernameRegLabel.setText(_translate("MainWindow", "Username"))
        self.passwordRegLabel.setText(_translate("MainWindow", "Password"))
        self.passwordRegLabel_2.setText(_translate("MainWindow", "Confirm Password"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.regButton.setText(_translate("MainWindow", "Register"))
        self.titleLabel.setText(_translate("MainWindow", "APU Workspace@Facial Emotion Recognition System"))

from View import res
